### ISSUE TITLE
Error with output from NHP-Surfaces_and Flatmaps.ipynb

### ISSUE THREAD

**Issue by clmcnabb** [VisionandCognition/NHP-Freesurfer#1]
I have run through the surfaces and flatmaps file twice now, using the Example_subject provided by the NMT v1.2 github repository linked from the notebook. Each time, the output has been incomplete with the majority missing. Throughout the running of align_and_process_singlesubject.sh I received warnings about the center of mass shift. Attached below is the output brain from the first step. 

[Example_Subject_brain.nii.gz](https://github.com/VisionandCognition/NHP-Freesurfer/files/6191044/Example_Subject_brain.nii.gz)

**Comment by pcklink** [comment]
The NMT v1.2 has been superseded by NMT v2.0 and a new script to process single-subject data based on AFNI's @animal_warper which has worked great in our lab. You can find the info on the AFNI site here: https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/nonhuman/macaque_tempatl/template_nmtv2.html

These NHP-Freesurfer have not yet been adjusted to the new version. Regardless, the problem you describe and the example you attached is something I've seen before and it indeed indicates a failure of the first step in the process: rigid body alignment of the single-subject data and the template. It should pretty much always get solved by separately performing a rigid alignment of your single subject (or example subject) to the template before using the pipeline. 

Let me know if this works for you and/or you decided to transition to the NMT v2.0 workflows.

**Comment by clmcnabb** [comment]
I've tried the AFNI pipeline  using NMT v2.0 and the @animal_warper, and it has worked great. Thank you for the help and suggestion!
